Repository Automattic/wp-e2e-tests, pull requests merged in 2018-11, with the labels that each got.

#1579 Update continue button on processing screen
  lib/pages/signup/signup-processing-page.js
Labels: canary change

#1577 Remove G-Suite upsell discount a/b test
  config/default.json
Labels: [Status] Ready to Merge

#1578 Remove media upload workaround for calypso.live
  specs/wp-media-upload-spec.js
  specs/wp-page-editor-spec.js
  specs/wp-post-editor-spec.js
Labels: [Status] Needs Review

#1580 Activate Jetpack module before adding Markdown block
  lib/pages/wp-admin/wp-admin-jetpack-modules-page.js
  specs-blocks/gutenberg-markdown-block-spec.js
Labels: [Status] Needs Review

#1585 Add 'Delete account' flow
  lib/flows/delete-account-flow.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1591 Add 'Delete plan' flow
  lib/flows/delete-plan-flow.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1589 Remove duplication of cart total selector
  lib/components/secure-payment-component.js
  lib/pages/plan-checkout-page.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1590 Update the signup flow test cases for Business users
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1593 Fix window width on mobile test runs
  lib/driver-manager.js
Labels: [Status] Needs Review

#1595 Try node 10.13.0 take 2
  .nvmrc
Labels: [Status] Needs Review

#1505 Remove xpath selectors
  lib/components/nav-bar-component.js
  lib/driver-helper.js
  lib/pages/plugins-browser-page.js
  lib/pages/posts-page.js
  lib/pages/reader-page.js
  lib/pages/stats/activity-page.js
  lib/pages/woocommerce/store-products-page.js
Labels: [Status] Needs Review, [Type] Enhancement

#1597 Fix Theme purchase test/cleanup
  lib/flows/delete-plan-flow.js
  lib/pages/purchases-page.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1598 Skip video recording if dependencies don't install
  .circleci/config.yml
Labels: [Status] Ready to Merge

#1602 Cleanup old A/B tests not running anymore
  config/default.json
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge

#1584 Updates test for import signup flow
  lib/pages/signup/import-from-url-page.js
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge

#1612 Add the `calypsoifyGutenberg` key to known tests.
  config/default.json
Labels: [Status] Ready to Merge

#1618 Gutenberg: Add the calypsoifyGutenberg A/B test
  config/default.json
Labels: [Status] Ready to Merge

#1619 Gutenberg: remove the calypsoifyGutenberg A/B test
  config/default.json
Labels: [Status] Needs Review

#1615 Update ie11 config to fix broken sauce labs tests
  config/default.json
  lib/driver-manager.js
  lib/mocha-hooks.js
Labels: [Status] Needs Review

#1621 Adds Gutenberg Editor Specs
  config/encrypted.enc
  lib/flows/login-flow.js
  lib/gutenberg/gutenberg-editor-header-component.js
  lib/pages/editor-page.js
  specs/wp-gutenberg-page-editor-spec.js
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] Needs Jetpack e2e Testing, [Type] Enhancement

#1622 Adding test to known Tests that was added in https://github.com/Autom…
  config/default.json
Labels: [Status] Ready to Merge

#1607 Try sign up flow for continue along
  lib/flows/sign-up-step.js
  specs/wp-signup-spec.js
Labels: Technical Debt, [Status] Ready to Merge, [Type] Enhancement

#1613 Disable video when running in headless mode.
  lib/video-recorder.js
  run.sh
Labels: [Status] Ready to Merge

#1623 Add Gutenberg post canary
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Type] Enhancement

#1608 Signup: change the order of steps in personal flow
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1616 Signup: update test cases as the premium flow changes
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge

#1617 Signup: update test cases as the business flow changes
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge

#1625 Gutenbergify: Check Activity Log for Public Post
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#1626 Update retry number and get screenshots working for IE11
  lib/mocha-hooks.js
  magellan-ie11-canary.json
  magellan-ie11.json
Labels: [Status] Needs Review

#1624 Add the first create page spec to use Gutenberg
  lib/flows/login-flow.js
  lib/gutenberg/gutenberg-editor-sidebar-component.js
  specs/wp-gutenberg-page-editor-spec.js
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] Blocked / Hold, [Status] Needs Review

#1632 Gutenberg: Trash post and Edit post tests
  lib/driver-helper.js
  lib/gutenberg/gutenberg-editor-header-component.js
  lib/gutenberg/gutenberg-editor-sidebar-component.js
  lib/pages/wp-admin/wp-admin-posts-page.js
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#1633 Gutenberg: Revert to draft test
  lib/gutenberg/gutenberg-editor-header-component.js
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#1634 [Gutenberg] Public Posts: Preview and Publish a Public Post
  lib/driver-helper.js
  lib/gutenberg/gutenberg-editor-component.js
  lib/gutenberg/gutenberg-editor-sidebar-component.js
  lib/gutenberg/gutenberg-preview-component.js
  specs-blocks/gutenberg-markdown-block-spec.js
  specs/wp-gutenberg-page-editor-spec.js
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#1631 Import Signup Flow: Fix & re-enable e2e test
  lib/pages/import-page.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1639 Gutenberg: Insert a contact form: @parallel
  lib/gutenberg/gutenberg-editor-component.js
  lib/gutenberg/gutenberg-preview-component.js
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] Ready to Merge

#1646 Gutenberg: Updating sections for permalink
  lib/gutenberg/gutenberg-editor-sidebar-component.js
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#1643 Patch Gutenberg contact form: await promises from shortcode element
  lib/gutenberg/gutenberg-editor-component.js
Labels: [Status] Needs Review

#1637 Gutenbergify: Schedule post
  lib/gutenberg/gutenberg-editor-component.js
  lib/gutenberg/gutenberg-editor-sidebar-component.js
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#1642 Gutenberg- Password protected posts
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#1638 Gutenberg: Public and Private pages
  lib/gutenberg/gutenberg-editor-component.js
  lib/gutenberg/gutenberg-editor-sidebar-component.js
  lib/gutenberg/gutenberg-page-preview-component.js
  lib/gutenberg/gutenberg-post-preview-component.js
  specs/wp-gutenberg-page-editor-spec.js
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#1650 Skip test if domains tests are disabled
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1653 Fix uploading images and adding alt text
  lib/gutenberg/gutenberg-editor-component.js
  lib/gutenberg/gutenberg-editor-sidebar-component.js
  specs/wp-gutenberg-page-editor-spec.js
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] Ready to Merge

#1651 Add Private Post Spec
  lib/gutenberg/gutenberg-editor-sidebar-component.js
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] Ready to Merge

#1654 Gutenberg: Updating selector used to publish
  lib/gutenberg/gutenberg-editor-component.js
Labels: [Type] Enhancement

#1652 Add Gutenberg in calypso canary test
  lib/data-helper.js
  lib/flows/login-flow.js
  lib/gutenberg/gutenberg-editor-component.js
  specs/wp-calypso-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#1657 Disable Trash Post
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#1656 Enable more Gutenberg in Calypso Posts
  lib/gutenberg/gutenberg-editor-component.js
  lib/gutenberg/gutenberg-editor-sidebar-component.js
  specs/wp-calypso-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#1659 Trash post - increase timeout
  lib/gutenberg/gutenberg-editor-sidebar-component.js
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#1660 Gutenberg in Calypso Page Editor Specs
  lib/flows/login-flow.js
  lib/gutenberg/gutenberg-editor-component.js
  lib/gutenberg/gutenberg-page-preview-component.js
  specs/wp-calypso-gutenberg-page-editor-spec.js
Labels: [Status] Needs Review

#1661 Add test for Simple Payments button
  lib/driver-helper.js
  lib/gutenberg/blocks/payment-block-component.js
  specs/wp-calypso-gutenberg-page-editor-spec.js
  specs/wp-calypso-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#1665 Trying to get ie11 canary to pass more reliably.
  lib/driver-helper.js
Labels: [Status] Needs Review

#1666 Match digest between encrypt and decrypt scripts
  config/encrypted.enc
  package.json
Labels: [Pri] High, [Status] Needs Review, [Type] Bug

#1667 A/B Test: Add new A/B test for domain suggestions
  config/default.json
Labels: [Status] Ready to Merge

#1675 Fix: Wait for tag to load
  lib/pages/view-post-page.js
Labels: [Status] Needs Review

#1670 [WIP] Add test for Embed urls
  lib/gutenberg/blocks/embeds-block-component.js
  lib/pages/view-post-page.js
  specs/wp-calypso-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#1680 Disable Gutenberg Editor: Public Posts
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review
