Repository Automattic/wp-e2e-tests, pull requests merged in 2018-04, with the labels that each got.

#1103 Prettify all the spec files
  specs-i18n/logged-out-redirect-i18n-spec.js
  specs-i18n/search-wordpress-on-google.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
  specs-jetpack-calypso/wp-jetpack-plans-spec.js
  specs-jetpack-calypso/wp-jetpack-plugins-spec.js
  specs-jetpack-calypso/wp-jetpack-settings-writing-media-spec.js
  specs-jetpack-calypso/wp-pressable-nux-spec.js
  specs-visdiff/wp-calypso-visdiff.js
  specs-woocommerce/wp-woocommerce-spec.js
  specs/wp-invite-users-spec.js
  specs/wp-log-in-out-spec.js
  specs/wp-manage-domains-spec.js
  specs/wp-media-upload-spec.js
  specs/wp-notifications-spec.js
  specs/wp-page-editor-spec.js
  specs/wp-plan-purchase-spec.js
  specs/wp-post-editor-spec.js
  specs/wp-reader-spec.js
  specs/wp-signup-spec.js
  specs/wp-theme-multisite-spec.js
  specs/wp-theme-switch-spec.js
  specs/wp-view-site-spec.js
Labels: [Status] Needs Review, [Type] Enhancement

#1111 Update node to 8.11.0 matching Calypso
  .circleci/config.yml
  .nvmrc
Labels: [Status] Needs Review, [Type] Task

#1107 Try to handle Jurassic Ninja errors
  lib/driver-helper.js
  lib/flows/login-flow.js
  lib/pages/wp-admin/wp-admin-customizer-page.js
  lib/pages/wp-admin/wp-admin-dashboard-page.js
  lib/pages/wp-admin/wp-admin-jetpack-page.js
  lib/pages/wp-admin/wp-admin-new-user-page.js
  lib/pages/wp-admin/wp-admin-plugin-popup.js
  lib/pages/wp-admin/wp-admin-plugins-page.js
  lib/pages/wp-admin/wp-admin-sidebar.js
  lib/pages/wp-admin/wp-admin-updates-page.js
  lib/pages/wporg-creator-page.js
Labels: [Status] Needs Review

#1115 Fix Pressable NUX flow
  README.md
  config/encrypted.enc
  docs/miscellaneous.md
  lib/flows/login-flow.js
  lib/pages/login-page.js
  lib/pages/pressable/pressable-sites-page.js
  specs-jetpack-calypso/wp-pressable-nux-spec.js
Labels: [Status] Needs Review

#1109 Add Jetpack onboarding tests
  lib/components/widget-contact-info-component.js
  lib/components/wizard-navigation-component.js
  lib/pages/jetpack-onboarding/activate-stats-page.js
  lib/pages/jetpack-onboarding/business-address-page.js
  lib/pages/jetpack-onboarding/contact-form-page.js
  lib/pages/jetpack-onboarding/install-woocommerce-page.js
  lib/pages/jetpack-onboarding/set-homepage-page.js
  lib/pages/jetpack-onboarding/site-title-tagline-page.js
  lib/pages/jetpack-onboarding/site-type-page.js
  lib/pages/jetpack-onboarding/summary-page.js
  specs-jetpack-calypso/wp-jetpack-onboarding-spec.js
Labels: [Status] Needs Review

#1112 Add circleci devDependency
  package-lock.json
  package.json
Labels: [Status] Needs Review, [Type] Task

#1117 Add test for Jetpack connection from WooCommerce wizard
  lib/pages/woocommerce/wizard-extras-page.js
  lib/pages/woocommerce/wizard-jetpack-page.js
  lib/pages/woocommerce/wizard-payments-page.js
  lib/pages/woocommerce/wizard-ready-page.js
  lib/pages/woocommerce/wizard-setup-page.js
  lib/pages/woocommerce/wizard-shipping-page.js
  lib/pages/wp-admin/wp-admin-dashboard-page.js
  lib/pages/wporg-creator-page.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
Labels: [Status] Needs Review

#1098 Increase retries for IE11 and try to fix some issues with processing
  magellan-ie11.json
  scripts/run-wrapper.sh
Labels: [Status] Needs Review

#1124 Update: Babel7 and preset-env
  .babelrc
  package-lock.json
  package.json
  test/mocha.opts
Labels: [Status] In Progress, [Status] Needs Review, [Type] Enhancement

#1133 Jetpack: Update the way we enter site URL in calypso
  lib/pages/add-new-site-page.js
Labels: workaround

#1130 Add support for domain registration redesign
  lib/components/find-a-domain-component.js
Labels: [Status] Ready to Merge

#1128 Add e2e test for money back guarantee
  config/default.json
Labels: [Status] Needs Review

#1142 Fix Pressable NUX spec, minor refactoring and styling
  .circleci/config.yml
  lib/pages/pressable/pressable-sites-page.js
  lib/pages/stats/activity-page.js
  specs-jetpack-calypso/wp-pressable-nux-spec.js
  test/mocha.opts
Labels: [Status] Ready to Merge

#1139 Use username for WP.com login in Jetpack SSO test
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
Labels: [Status] Ready to Merge

#1095 Add/jetpack remote install spec
  lib/components/widget-contact-info-component.js
  lib/components/wizard-navigation-component.js
  lib/flows/jetpack-connect-flow.js
  lib/pages/jetpack-authorize-page.js
  lib/pages/jetpack-onboarding/activate-stats-page.js
  lib/pages/jetpack-onboarding/business-address-page.js
  lib/pages/jetpack-onboarding/contact-form-page.js
  lib/pages/jetpack-onboarding/install-woocommerce-page.js
  lib/pages/jetpack-onboarding/set-homepage-page.js
  lib/pages/jetpack-onboarding/site-title-tagline-page.js
  lib/pages/jetpack-onboarding/site-type-page.js
  lib/pages/jetpack-onboarding/summary-page.js
  lib/pages/jetpack/jetpack-connect-add-credentials-page.js
  lib/pages/themes-page.js
  lib/pages/woocommerce/wizard-extras-page.js
  lib/pages/woocommerce/wizard-jetpack-page.js
  lib/pages/woocommerce/wizard-payments-page.js
  lib/pages/woocommerce/wizard-ready-page.js
  lib/pages/woocommerce/wizard-setup-page.js
  lib/pages/woocommerce/wizard-shipping-page.js
  lib/pages/wporg-creator-page.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
  specs-jetpack-calypso/wp-jetpack-onboarding-spec.js
Labels: [Status] Needs Review

#1137 Add support for domain register redesign take 2
  lib/components/find-a-domain-component.js
Labels: [Status] Ready to Merge

#1147 Rename the Upgrade Pricing Display test
  config/default.json
Labels: [Status] Ready to Merge

#1149 Decrease repeat time for magellan tests
  magellan-jetpack.json
Labels: [Status] Needs Review

#1153 Remove promise from shopping-cart-widget-component.js and add async/await
  lib/components/shopping-cart-widget-component.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1158 Update magellan browser for IE11
  magellan-ie11-canary.json
  magellan-ie11.json
Labels: [Status] Ready to Merge, [Type] Enhancement

#1154 Add async/await into /specs
  specs/wp-log-in-out-spec.js
  specs/wp-manage-domains-spec.js
  specs/wp-notifications-spec.js
  specs/wp-plan-purchase-spec.js
  specs/wp-reader-spec.js
  specs/wp-signup-spec.js
  specs/wp-theme-multisite-spec.js
  specs/wp-theme-switch-spec.js
  specs/wp-view-site-spec.js
Labels: [Status] Ready to Merge

#1159 Fix Free Plan selection during Signup
  lib/pages/signup/pick-a-plan-page.js
Labels: [Pri] High, [Type] Bug

#1162 Add async/await into /specs/wp-invite-users-spec.js
  specs/wp-invite-users-spec.js
Labels: [Status] Ready to Merge

#1164 Add async/await into /specs/wp-post-editor-spec.js
  lib/components/post-editor-sidebar-component.js
  lib/components/post-editor-toolbar-component.js
  lib/pages/editor-page.js
  lib/pages/view-post-page.js
  specs/wp-post-editor-spec.js
Labels: [Status] Ready to Merge

#1168 Add async/await into /wp-media-upload-spec.js and /wp-page-editor-spec.js
  lib/pages/editor-page.js
  lib/pages/view-page-page.js
  specs/wp-media-upload-spec.js
  specs/wp-page-editor-spec.js
Labels: [Status] Ready to Merge

#1157 Add support for Jetpack bleeding edge site
  config/encrypted.enc
Labels: [Status] Ready to Merge

#1165 Update docs for wrapper repos
  docs/miscellaneous.md
Labels: [Status] Ready to Merge
