Repository Automattic/wp-e2e-tests, pull requests merged in 2018-06, with the labels that each got.

#1238 Update node to 8.11.2
  .babelrc
  .circleci/config.yml
  .nvmrc
Labels: [Status] Needs Review, [Type] Task

#1241 Needed changes for disabled promise manager
  lib/base-container.js
  lib/components/editor-confirmation-sidebar-component.js
  lib/components/enter-a-domain-component.js
  lib/components/find-a-domain-component.js
  lib/components/navbar-component.js
  lib/components/notices-component.js
  lib/components/notifications-component.js
  lib/components/page-preview-component.js
  lib/components/post-editor-sidebar-component.js
  lib/components/post-editor-toolbar-component.js
  lib/components/post-preview-component.js
  lib/components/secure-payment-component.js
  lib/components/sidebar-component.js
  lib/components/signup-step-component.js
  lib/components/site-view-component.js
  lib/driver-helper.js
  lib/driver-manager.js
  lib/flows/login-flow.js
  lib/pages/accept-invite-page.js
  lib/pages/cancel-domain-page.js
  lib/pages/cancel-purchase-page.js
  lib/pages/disconnect-survey-page.js
  lib/pages/domain-details-page.js
  lib/pages/domain-only-settings-page.js
  lib/pages/domains-page.js
  lib/pages/edit-team-member-page.js
  lib/pages/editor-page.js
  lib/pages/gsuite-upsell-page.js
  lib/pages/invite-people-page.js
  lib/pages/login-page.js
  lib/pages/magic-login-page.js
  lib/pages/manage-purchase-page.js
  lib/pages/not-found-page.js
  lib/pages/people-page.js
  lib/pages/profile-page.js
  lib/pages/purchases-page.js
  lib/pages/reader-page.js
  lib/pages/revoke-page.js
  lib/pages/signup/about-page.js
  lib/pages/signup/checkout-page.js
  lib/pages/signup/checkout-thankyou-page.js
  lib/pages/signup/choose-a-theme-page.js
  lib/pages/signup/create-your-account-page.js
  lib/pages/signup/domain-first-page.js
  lib/pages/signup/pick-a-plan-page.js
  lib/pages/signup/signup-processing-page.js
  lib/pages/signup/view-blog-page.js
  lib/pages/theme-detail-page.js
  lib/pages/theme-preview-page.js
  lib/pages/themes-page.js
  lib/pages/view-page-page.js
  lib/pages/view-post-page.js
  lib/pages/wp-home-page.js
  scripts/run-wrapper.sh
  specs/wp-invite-users-spec.js
  specs/wp-media-upload-spec.js
  specs/wp-page-editor-spec.js
  specs/wp-post-editor-spec.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1249 Set slackChannelForScreenshots for visdiff tests
  config/encrypted.enc
Labels: [Status] Needs Review, visdiffs

#1254 Re-enabling the domain tests
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1247 Try deleting new accounts as we create them
  lib/pages/account/account-settings-page.js
  lib/pages/account/close-account-page.js
  lib/pages/profile-page.js
  lib/pages/purchases-page.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1251 Removed unused customizer code
  lib/pages/customizer-page.js
Labels: [Status] Needs Review, [Type] Task

#1250 Update npm dependencies
  package-lock.json
  package.json
Labels: [Status] Needs Review, [Type] Task

#1260 Fix IE11 canary issues
  config/default.json
  magellan-ie11.json
  specs/wp-signup-spec.js
Labels: [Type] Task

#1255 Fix failing jetpack tests
  lib/components/post-editor-sidebar-component.js
  lib/components/post-preview-component.js
  lib/components/sidebar-component.js
  lib/driver-helper.js
  lib/email-client.js
  lib/flows/jetpack-connect-flow.js
  lib/pages/editor-page.js
  lib/pages/jetpack/jetpack-connect-page.js
  lib/pages/posts-page.js
  lib/pages/themes-page.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
  specs-jetpack-calypso/wp-jetpack-onboarding-spec.js
  specs-jetpack-calypso/wp-pressable-nux-spec.js
  specs/wp-post-editor-spec.js
Labels: [Status] Needs Review

#1258 Try async base container
  lib/async-base-container.js
  lib/components/logged-out-masterbar-component.js
  lib/flows/login-flow.js
  lib/flows/pressable-nux-flow.js
  lib/pages/login-page.js
  lib/pages/wp-admin/wp-admin-logon-page.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
  specs/wp-invite-users-spec.js
  specs/wp-log-in-out-spec.js
  specs/wp-signup-spec.js
  specs/wp-theme-switch-spec.js
Labels: [Status] Needs Review, [Type] Enhancement

#1261 Fix Jetpack login issues
  lib/flows/login-flow.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
Labels: [Status] Needs Review

#1259 Skip tests if env variable is true
  docs/config.md
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge

#1262 Update sign up tests to use async pages
  lib/async-base-container.js
  lib/components/find-a-domain-component.js
  lib/components/secure-payment-component.js
  lib/components/signup-step-component.js
  lib/flows/jetpack-connect-flow.js
  lib/flows/sign-up-flow.js
  lib/pages/account/close-account-page.js
  lib/pages/landing-page.js
  lib/pages/magic-login-page.js
  lib/pages/signup/about-page.js
  lib/pages/signup/create-your-account-page.js
  lib/pages/signup/pick-a-plan-page.js
  lib/pages/signup/signup-processing-page.js
  lib/pages/signup/start-page.js
  lib/pages/signup/view-blog-page.js
  lib/pages/theme-detail-page.js
  lib/pages/themes-page.js
  lib/pages/wp-home-page.js
  scripts/jetpack/wp-jetpack-activate.js
  specs-i18n/logged-out-redirect-i18n-spec.js
  specs-i18n/search-wordpress-on-google.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
  specs-jetpack-calypso/wp-jetpack-onboarding-spec.js
  specs-jetpack-calypso/wp-jetpack-plans-spec.js
  specs/wp-invite-users-spec.js
  specs/wp-log-in-out-spec.js
  specs/wp-manage-domains-spec.js
  specs/wp-signup-spec.js
  specs/wp-theme-multisite-spec.js
  specs/wp-theme-switch-spec.js
Labels: [Status] Needs Review

#1263 Update invite spec
  lib/async-base-container.js
  lib/components/nav-bar-component.js
  lib/components/no-sites-component.js
  lib/components/notices-component.js
  lib/components/post-editor-toolbar-component.js
  lib/flows/login-flow.js
  lib/flows/sign-up-flow.js
  lib/pages/accept-invite-page.js
  lib/pages/edit-team-member-page.js
  lib/pages/editor-page.js
  lib/pages/invite-error-page.js
  lib/pages/invite-people-page.js
  lib/pages/people-page.js
  lib/pages/posts-page.js
  lib/pages/private-site-login-page.js
  lib/pages/reader-page.js
  lib/pages/revoke-page.js
  specs-jetpack-calypso/wp-jetpack-plans-spec.js
  specs-jetpack-calypso/wp-pressable-nux-spec.js
  specs-visdiff/wp-calypso-visdiff.js
  specs-woocommerce/wp-woocommerce-spec.js
  specs/wp-invite-users-spec.js
  specs/wp-log-in-out-spec.js
  specs/wp-manage-domains-spec.js
  specs/wp-media-upload-spec.js
  specs/wp-notifications-spec.js
  specs/wp-page-editor-spec.js
  specs/wp-post-editor-spec.js
  specs/wp-reader-spec.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review, [Type] Enhancement

#1265 Async more pages
  lib/components/enter-a-domain-component.js
  lib/components/map-a-domain-component.js
  lib/components/notifications-component.js
  lib/components/post-editor-sidebar-component.js
  lib/components/post-preview-component.js
  lib/components/shopping-cart-widget-component.js
  lib/components/sidebar-component.js
  lib/flows/jetpack-connect-flow.js
  lib/flows/login-flow.js
  lib/pages/domain-map-checkout-page.js
  lib/pages/domain-map-page.js
  lib/pages/domain-my-own-page.js
  lib/pages/domains-page.js
  lib/pages/invite-people-page.js
  lib/pages/pressable/pressable-sites-page.js
  lib/pages/profile-page.js
  lib/pages/signup/checkout-page.js
  lib/pages/stats-page.js
  lib/pages/view-post-page.js
  lib/pages/view-site-page.js
  scripts/jetpack/wp-jetpack-deactivate.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
  specs-jetpack-calypso/wp-jetpack-onboarding-spec.js
  specs-jetpack-calypso/wp-jetpack-plans-spec.js
  specs-jetpack-calypso/wp-pressable-nux-spec.js
  specs-visdiff/wp-calypso-visdiff.js
  specs-woocommerce/wp-woocommerce-spec.js
  specs/wp-log-in-out-spec.js
  specs/wp-manage-domains-spec.js
  specs/wp-media-upload-spec.js
  specs/wp-notifications-spec.js
  specs/wp-page-editor-spec.js
  specs/wp-plan-purchase-spec.js
  specs/wp-post-editor-spec.js
  specs/wp-reader-spec.js
  specs/wp-signup-spec.js
  specs/wp-theme-multisite-spec.js
  specs/wp-theme-switch-spec.js
  specs/wp-view-site-spec.js
Labels: [Status] Needs Review

#1266 Update/async pages
  lib/components/editor-confirmation-sidebar-component.js
  lib/components/payment-button-front-end-component.js
  lib/components/post-editor-toolbar-component.js
  lib/components/theme-dialog-component.js
  lib/components/widget-contact-info-component.js
  lib/components/wizard-navigation-component.js
  lib/pages/signup/domain-first-page.js
  lib/pages/view-page-page.js
  lib/pages/view-post-page.js
  specs-jetpack-calypso/wp-jetpack-onboarding-spec.js
  specs/wp-post-editor-spec.js
  specs/wp-signup-spec.js
  specs/wp-theme-multisite-spec.js
  specs/wp-theme-switch-spec.js
Labels: [Status] Needs Review

#1268 Fix Jetpack Async Specs
  lib/components/sidebar-component.js
  lib/flows/jetpack-connect-flow.js
  lib/pages/add-new-site-page.js
  lib/pages/jetpack-authorize-page.js
  lib/pages/pressable/pressable-site-settings-page.js
  lib/pages/wp-admin/wp-admin-new-user-page.js
  lib/pages/wp-admin/wp-admin-sidebar.js
  scripts/jetpack/wp-jetpack-activate.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
  specs-jetpack-calypso/wp-jetpack-onboarding-spec.js
  specs-jetpack-calypso/wp-jetpack-plans-spec.js
  specs-jetpack-calypso/wp-pressable-nux-spec.js
Labels: [Status] Needs Review

#1273 Update plan selector
  config/default.json
  lib/pages/signup/pick-a-plan-page.js
Labels: [Type] Task

#1272 Try warning when domains disabled
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1275 Remove API dependencies
  config/api.json
  docs/running-tests.md
  lib/wpcom-api/media.js
  lib/wpcom-api/oauth.js
  package-lock.json
  package.json
  run.sh
  scripts/i18n-screenshots-upload.js
Labels: [Status] Needs Review

#1276 Async More Pages and Components
  lib/components/current-theme-component.js
  lib/components/page-preview-component.js
  lib/components/post-editor-toolbar-component.js
  lib/components/post-preview-component.js
  lib/components/reader-sidebar-component.js
  lib/components/site-selector-component.js
  lib/components/site-view-component.js
  lib/pages/account/account-settings-page.js
  lib/pages/cancel-domain-page.js
  lib/pages/cancel-purchase-page.js
  lib/pages/customizer-page.js
  lib/pages/domain-details-page.js
  lib/pages/domain-only-settings-page.js
  lib/pages/external/paypal-checkout-page.js
  lib/pages/gsuite-upsell-page.js
  lib/pages/manage-purchase-page.js
  lib/pages/not-found-page.js
  lib/pages/plans-page.js
  lib/pages/profile-page.js
  lib/pages/purchases-page.js
  lib/pages/reader-manage-page.js
  lib/pages/signup/checkout-thankyou-page.js
  lib/pages/signup/choose-a-theme-page.js
  lib/pages/signup/next-steps-page.js
  lib/pages/stats/activity-page.js
  lib/pages/theme-preview-page.js
  lib/pages/twitter-feed-page.js
  lib/pages/view-page-page.js
  lib/pages/woocommerce/store-products-import-page.js
  lib/pages/woocommerce/store-stats-page.js
  lib/pages/wp-admin/wp-admin-customizer-page.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
  specs-jetpack-calypso/wp-jetpack-onboarding-spec.js
  specs-jetpack-calypso/wp-jetpack-plans-spec.js
  specs/wp-page-editor-spec.js
  specs/wp-plan-purchase-spec.js
  specs/wp-post-editor-spec.js
  specs/wp-reader-spec.js
  specs/wp-signup-spec.js
  specs/wp-theme-multisite-spec.js
  specs/wp-theme-switch-spec.js
  specs/wp-view-site-spec.js
Labels: [Status] Needs Review, [Type] Enhancement

#1277 Update Jetpack Connect User
  config/encrypted.enc
  specs/wp-theme-switch-spec.js
Labels: [Type] Enhancement

#1279 Precommit: Prevent eslint printing help when no files to lint
  scripts/pre-commit-hook.js
Labels: [Status] Needs Review, [Type] Bug

#1280 Increase timeout for Jetpack disconnect
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
  specs-jetpack-calypso/wp-pressable-nux-spec.js
Labels: [Status] Needs Review

#1269 Update to Node 10
  .babelrc
  .circleci/config.yml
  .nvmrc
  package-lock.json
Labels: [Status] Needs Review, [Type] Enhancement, [Type] Task

#1281 A/B Tests: Add staleCartNotice test
  config/default.json
Labels: [Status] Ready to Merge

#1286 Update/jetpack onboarding specs
  lib/pages/jetpack-onboarding/activate-stats-page.js
  lib/pages/jetpack-onboarding/business-address-page.js
  lib/pages/jetpack-onboarding/contact-form-page.js
  lib/pages/jetpack-onboarding/install-woocommerce-page.js
  lib/pages/jetpack-onboarding/set-homepage-page.js
  lib/pages/jetpack-onboarding/site-title-tagline-page.js
  lib/pages/jetpack-onboarding/site-type-page.js
  lib/pages/jetpack-onboarding/summary-page.js
  lib/pages/wporg-creator-page.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
  specs-jetpack-calypso/wp-jetpack-onboarding-spec.js
Labels: [Status] Needs Review

#1287 Update logged out home page selector
  lib/components/logged-out-masterbar-component.js
Labels: [Type] Task

#1288 Bye bye base container
  docs/style-guide.md
  lib/base-container.js
  lib/components/sidebar-component.js
  lib/flows/google-flow.js
  lib/pages/comments-page.js
  lib/pages/devdocs-page.js
  lib/pages/disconnect-survey-page.js
  lib/pages/external/google-ad-preview-tool.js
  lib/pages/external/google-search.js
  lib/pages/external/jetpackcom-features-design-page.js
  lib/pages/external/jetpackcom-pricing-page.js
  lib/pages/jetpack-com-debug-page.js
  lib/pages/jetpack-connect-install-page.js
  lib/pages/jetpack-onboarding/activate-stats-page.js
  lib/pages/jetpack-plans-sales-page.js
  lib/pages/pages-page.js
  lib/pages/plugin-details-page.js
  lib/pages/plugins-browser-page.js
  lib/pages/plugins-page.js
  lib/pages/pressable/pressable-approve-page.js
  lib/pages/pressable/pressable-logon-page.js
  lib/pages/settings-page.js
  lib/pages/wp-admin/wp-admin-plugin-popup.js
  lib/pages/wp-admin/wp-admin-plugins-page.js
  lib/pages/wp-admin/wp-admin-updates-page.js
  scripts/jetpack/wp-jetpack-activate.js
  scripts/jetpack/wp-jetpack-deactivate.js
  specs-i18n/search-wordpress-on-google.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
  specs-jetpack-calypso/wp-jetpack-plans-spec.js
  specs-jetpack-calypso/wp-jetpack-plugins-spec.js
  specs-jetpack-calypso/wp-jetpack-settings-writing-media-spec.js
  specs-jetpack-calypso/wp-pressable-nux-spec.js
  specs-visdiff/wp-calypso-visdiff.js
Labels: [Status] Needs Review

#1283 Update Dependencies
  package-lock.json
  package.json
Labels: [Status] Ready to Merge

#1293 put this.driver instead of self.driver
  lib/pages/plugins-browser-page.js
Labels: [Status] Needs Review

#1289 Remove serverpilot and local docker
  .circleci/config.yml-jetpack
  README.md
  docker-compose/docker-compose-calypso.yml
  docker-compose/docker-compose-hub-calypso.yml
  docker-compose/docker-compose-hub-circleci.yml
  docker-compose/docker-compose-hub.yml
  docs/config.md
  docs/miscellaneous.md
  docs/running-tests.md
  package-lock.json
  package.json
  scripts/jetpack/wp-serverpilot-delete-all.js
  scripts/jetpack/wp-serverpilot-delete.js
  scripts/jetpack/wp-serverpilot-init.js
Labels: [Status] Needs Review

#1297 put this.driver instead of self.driver #2
  lib/pages/plugins-browser-page.js
Labels: [Status] Needs Review

#1246 Disable promise manager
  lib/driver-helper.js
  lib/pages/account/close-account-page.js
  run.sh
  scripts/run-wrapper.sh
  specs/wp-theme-switch-spec.js
Labels: [Status] Needs Review

#1299 Update style guide for async/await
  docs/style-guide.md
Labels: [Status] Needs Review

#1296 Update assert.equal
  lib/async-base-container.js
  lib/pages/landing-page.js
  lib/pages/wp-home-page.js
  specs-jetpack-calypso/wp-jetpack-onboarding-spec.js
  specs-jetpack-calypso/wp-jetpack-plugins-spec.js
  specs-visdiff/wp-calypso-visdiff.js
  specs/wp-invite-users-spec.js
  specs/wp-log-in-out-spec.js
  specs/wp-notifications-spec.js
  specs/wp-page-editor-spec.js
  specs/wp-post-editor-spec.js
  specs/wp-reader-spec.js
  specs/wp-signup-spec.js
  specs/wp-theme-multisite-spec.js
  specs/wp-theme-switch-spec.js
  specs/wp-view-site-spec.js
Labels: Technical Debt, [Status] Needs Review

#1298 CircleCI: Fix key -> keys list
  .circleci/config.yml
Labels: [Status] Needs Review, [Type] Bug

#1305 Cater for both skip free plan and selecting free plan
  lib/driver-helper.js
  lib/pages/signup/pick-a-plan-page.js
Labels: [Status] Needs Review, canary change

#1306 Remove Chai
  package-lock.json
  package.json
  specs/wp-theme-multisite-spec.js
Labels: Technical Debt, [Status] Needs Review

#1311 Update Login Flow to not Visit the Reader Page
  lib/flows/login-flow.js
Labels: Technical Debt, [Status] Needs Review, [Type] Enhancement

#1315 Disable promise manager in Mocha
  test/mocha.env.js
  test/mocha.opts
Labels: [Status] Needs Review, [Type] Task

#1317 Update Node to 10.5.0
  .babelrc
  .circleci/config.yml
  .nvmrc
Labels: [Status] Needs Review, [Type] Task
