Repository Automattic/wp-e2e-tests, pull requests merged in 2018-10, with the labels that each got.

#1492 Gutenpack: Add MVP Markdown block test
  lib/gutenberg/blocks/gutenberg-block-component.js
  lib/gutenberg/blocks/markdown-block-component.js
  lib/gutenberg/gutenberg-editor-header-component.js
  lib/pages/frontend/post-area-component.js
  lib/pages/wp-admin/wp-admin-sidebar.js
  lib/pages/wporg-creator-page.js
  specs-blocks/gutenberg-blocks-spec.js
Labels: [Status] Needs Review, [Type] Enhancement

#1508 Updating node version to match wp-calypso
  .nvmrc
Labels: [Status] Ready to Merge

#1510 Make Gutenberg post publish more reliable
  lib/gutenberg/gutenberg-editor-header-component.js
  specs-blocks/gutenberg-blocks-spec.js
Labels: [Status] Ready to Merge

#1511 Include Gutenberg tests in Jetpack CI suite
  magellan-jetpack.json
  specs-blocks/gutenberg-blocks-spec.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1513 Add Gutenberg block test creation docs
  README.md
  docs/gutenberg.md
  specs-blocks/gutenberg-markdown-block-spec.js
Labels: [Status] Ready to Merge

#1516 Remove readerSearchPlaceholder from A/B test overrides
  config/default.json
Labels: [Status] Ready to Merge

#1521 Use an env var for the circleci image.
  .circleci/config.yml
  scripts/circleci-branch-update.sh
Labels: [Status] Needs Review

#1502 Try selenium 4.0.0-alpha.1
  lib/components/secure-payment-component.js
  package-lock.json
  package.json
Labels: [Status] Ready to Merge

#1523 Try to fix the sign up about form submit
  lib/pages/signup/about-page.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1518 Remove duplicate Markdown block spec file
  specs-blocks/gutenberg-blocks-spec.js
Labels: [Status] Ready to Merge

#1526 Fix mobile signup issues
  lib/components/secure-payment-component.js
  lib/pages/signup/about-page.js
Labels: [Status] Needs Review

#1528 Clean up login page
  lib/pages/login-page.js
Labels: [Status] Needs Review, [Type] Enhancement

#1533 Update node version when updating nvmrc file
  .circleci/config.yml
  scripts/circleci-branch-update.sh
Labels: [Status] Ready to Merge

#1532 Fix few Jetpack-related tests
  lib/pages/frontend/comments-area-component.js
  lib/pages/wp-admin/wp-admin-dashboard-page.js
Labels: [Status] Ready to Merge

#1519 Run Gutenpack tests against JN site which includes PR changes
  docs/running-tests.md
  lib/data-helper.js
  lib/pages/wporg-creator-page.js
  run.sh
  scripts/run-wrapper.sh
Labels: [Status] Needs Review

#1514 Update tests to use new user first signup flow
  config/default.json
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1539 Updating chromedriver to work with chrome 70
  package-lock.json
  package.json
Labels: [Status] Needs Review

#1542 i18n tests: Use setRect() instead setSize() to set browser size
  lib/driver-manager.js
Labels: [Status] Needs Review, [Type] Bug

#1535 Test import in signup flow
  lib/pages/import-page.js
  lib/pages/signup/import-from-url-page.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review, [Type] Enhancement

#1547 Add pauseBetweenKeysMS to setWhenSettable()
  lib/components/secure-payment-component.js
  lib/driver-helper.js
Labels: [Status] Needs Review, [Type] Enhancement

#1553 Override `improvedOnboarding` abtest as `main`
  config/default.json
Labels: [Status] Needs Review

#1558 Remove mobile emulation
  lib/driver-manager.js
Labels: [Status] Needs Review

#1559 Domains: Add skip domain or step test
  config/default.json
Labels: [Status] Needs Review

#1561 Set 1ms timeout between keys
  lib/components/secure-payment-component.js
  lib/driver-helper.js
Labels: [Status] Needs Review

#1560 Adds a sign up for site scenario for logged in customer
  lib/components/no-sites-component.js
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1540 Find element by text and click on it
  lib/components/notifications-component.js
  lib/driver-helper.js
  lib/pages/themes-page.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1548 Use data-e2e attributes for Sidebar items
  lib/components/sidebar-component.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1571 Fix/jetpack failing tests
  lib/components/nav-bar-component.js
  lib/flows/login-flow.js
  lib/gutenberg/blocks/markdown-block-component.js
  lib/pages/woocommerce/woo-wizard-shipping-page.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
Labels: [Status] Needs Review

#1574 Try transfer domain test
  specs/wp-manage-domains-spec.js
Labels: [Status] Ready to Merge

#1573 Add a Reader signup e2e scenario
  lib/pages/signup/reader-landing-page.js
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge
