Repository Automattic/wp-e2e-tests, pull requests merged in 2018-08, with the labels that each got.

#1375 Update/jetpack async driver helper
  docs/miscellaneous.md
  lib/pages/jetpack-authorize-page.js
  lib/pages/jetpack-onboarding/business-address-page.js
  lib/pages/jetpack-onboarding/contact-form-page.js
  lib/pages/pressable/pressable-site-settings-page.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1380 Update hardcoded wait to relative explicit wait
  docs/style-guide.md
  lib/pages/transfer-domain-precheck-page.js
Labels: Technical Debt

#1381 Temporarily disable transfer domain spec
  specs/wp-manage-domains-spec.js
Labels: workaround

#1373 Skip domains tests if domain registration is unavailable
  lib/components/domain-registration-unavailable-component.js
  lib/components/new-user-domain-registration-unavailable-component.js
  lib/components/purchase-domain-only-component.js
  lib/pages/signup/search-domains-page.js
  specs/wp-manage-domains-spec.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1384 Disable test
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1385 Remove /domains as a start page and revert to previous state
  lib/components/purchase-domain-only-component.js
  lib/pages/signup/search-domains-page.js
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge

#1378 Add `gsuiteDiscount` abtest to the defaut config.
  config/default.json
Labels: [Status] Ready to Merge

#1392 Add basic import scenario
  lib/components/sidebar-component.js
  lib/pages/settings/importer-page.js
  specs/wp-import-site-spec.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1394 Try clicking theme screenshot
  lib/pages/theme-detail-page.js
Labels: [Status] Ready to Merge, workaround

#1395 Updates an existing scenario to start from the /jetpack/new route
  lib/pages/signup/jetpack-add-new-site-page.js
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1389 Remove scheduled post when test is finished
  specs/wp-post-editor-spec.js
Labels: [Status] Needs Review

#1398 Delete .art.blog site
  lib/pages/settings-page.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review, [Type] Enhancement

#1387 Add videos to test runs in CircleCI
  .circleci/config.yml
  lib/driver-manager.js
  lib/mocha-hooks.js
  lib/video-recorder.js
  scripts/run-wrapper.sh
  test/mocha.opts
Labels: [Status] Needs Review, [Type] Task

#1401 Skip test if domain registration is unavailable
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1396 Try/jetpack onboarding custom data type
  lib/components/wizard-navigation-component.js
  lib/pages/jetpack-onboarding/activate-stats-page.js
  lib/pages/jetpack-onboarding/contact-form-page.js
  lib/pages/jetpack-onboarding/set-homepage-page.js
  lib/pages/jetpack-onboarding/site-title-tagline-page.js
  lib/pages/jetpack-onboarding/site-type-page.js
  lib/pages/jetpack-onboarding/summary-page.js
  specs-jetpack-calypso/wp-jetpack-onboarding-spec.js
Labels: [Status] Needs Review, [Type] Enhancement

#1406 Add simple frontend comment test
  lib/components/post-editor-toolbar-component.js
  lib/pages/frontend/comments-area-component.js
  specs/wp-comments-spec.js
Labels: [Status] Needs Review

#1400 Stability improvements for Jetpack Connect tests
  lib/async-base-container.js
  lib/driver-helper.js
  lib/flows/jetpack-connect-flow.js
  lib/flows/login-flow.js
  lib/pages/woocommerce/woo-wizard-jetpack-page.js
  lib/pages/wp-admin/wp-admin-customizer-page.js
  lib/pages/wp-admin/wp-admin-dashboard-page.js
  lib/pages/wp-admin/wp-admin-new-user-page.js
  lib/pages/wporg-creator-page.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
  specs/wp-theme-switch-spec.js
Labels: [Status] Needs Review

#1390 Set cookie to hide GDPR banner regardless of location
  lib/driver-manager.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1415 Update node version
  .circleci/config.yml
  .nvmrc
Labels: [Status] Needs Review

#1420 Add test coupon code
  config/encrypted.enc
Labels: [Status] Ready to Merge

#1419 Fix activity log test
  lib/pages/stats/activity-page.js
  specs/wp-post-editor-spec.js
Labels: [Status] Ready to Merge

#1411 Run comment test in CI
  lib/components/post-editor-toolbar-component.js
  lib/pages/frontend/comments-area-component.js
  specs/wp-comments-spec.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1427 Remove visdiff support from the repo
  config/encrypted.enc
  config/local.example.json
  docs/config.md
  docs/running-tests.md
  lib/eyes-helper.js
  lib/pages/profile-page.js
  magellan-visdiff.json
  package.json
  run.sh
  specs/wp-log-in-out-spec.js
Labels: [Status] Ready to Merge, visdiffs

#1416 Change the signup spec as we're going to rollout the checklist to other goal types
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge

#1429 Reader: add a check that a reader comment appears
  lib/pages/reader-page.js
  specs/wp-reader-spec.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1434 Fix the signup tests to include a canary
  specs/wp-signup-spec.js
Labels: [Pri] High

#1428 Shorten theme test to avoid theme switch collisions
  lib/pages/theme-detail-page.js
  lib/pages/theme-preview-page.js
  specs/wp-theme-switch-spec.js
Labels: [Status] Ready to Merge

#1430 Replace nudgeAPalooza 5-way test with 4 smaller 2-way tests
  config/default.json
Labels: [Status] In Progress

#1438 Fix known test keys
  config/default.json
Labels: [Status] Needs Review

#1442 Temporarily remove sign up canary test
  specs/wp-signup-spec.js
Labels: workaround

#1445 Temp: disable transfer domain test
  specs/wp-manage-domains-spec.js
Labels: workaround

#1440 Fixing broken account cleanup steps
  lib/pages/profile-page.js
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge

#1433 Re-enable sign up activation emails in sign up tests
  lib/pages/editor-page.js
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1447 Try increasing log in timeout check
  lib/pages/login-page.js
Labels: [Status] Ready to Merge

#1450 Remove report.sh
  scripts/report.sh
Labels: [Status] Needs Review

#1451 Renable domains transfer test
  specs/wp-manage-domains-spec.js
Labels: [Type] Task

#1448 Remove unused approvePushToken function
  lib/push-client.js
Labels: [Status] Ready to Merge
