Repository Automattic/wp-e2e-tests, pull requests merged in 2018-02, with the labels that each got.

#918 Add linting pre-commit hook take 2
  .gitignore
  package.json
Labels: enhancement

#911 Try switching jetpack tests to Jurassic Ninja
  .gitignore
  lib/components/sidebar-component.js
  lib/data-helper.js
  lib/flows/jetpack-connect-flow.js
  lib/flows/login-flow.js
  lib/pages/disconnect-survey-page.js
  lib/pages/signup/pick-a-plan-page.js
  lib/pages/wp-admin/wp-admin-dashboard-page.js
  lib/pages/wporg-creator-page.js
  scripts/jetpack/wp-jetpack-jn-activate.js
  specs/wp-post-editor-spec.js
Labels: [Status] Needs Review, enhancement

#912 Login: Add test for push 2fa case
  lib/push-client.js
  package-lock.json
  package.json
  specs/wp-log-in-out-spec.js
Labels: [Status] Ready to Merge

#924 Remove: G Suite Upsell V2 test from the configuration.
  config/default.json
  lib/pages/gsuite-upsell-page.js
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge

#927 Use Jetpack master branch for JN tests
  lib/flows/jetpack-connect-flow.js
  lib/pages/wporg-creator-page.js
Labels: enhancement

#919 Use encrypted config to store credentials
  .circleci/config.yml
  config/encrypted.enc
  docs/config.md
  docs/miscellaneous.md
  docs/running-tests.md
  lib/data-helper.js
  lib/reporter/magellan-reporter.js
  lib/slack-notifier.js
  package.json
Labels: [Status] Needs Review, enhancement

#937 Fix TARGET env var
  lib/data-helper.js
  lib/reporter/magellan-reporter.js
Labels: bug

#936 Add live branch support to logged out theme page
  lib/pages/themes-page.js
Labels: task

#941 Add new test
  config/default.json
Labels: [Status] Ready to Merge

#953 Set the domain suggestion group
  config/default.json
Labels: task

#954 Override AB test groups when logged in
  lib/flows/login-flow.js
  lib/pages/jetpack-authorize-page.js
  specs/wp-invite-users-spec.js
  specs/wp-manage-domains-map-spec.js
  specs/wp-manage-domains-spec.js
  specs/wp-post-editor-spec.js
Labels: task

#955 Upgrade node to 8.9.4
  .nvmrc
Labels: [Status] Needs Review, task

#952 Try removing HTTPS hosts
  config/default.json
  lib/components/post-editor-toolbar-component.js
  package-lock.json
  package.json
  specs/wp-page-editor-spec.js
  specs/wp-post-editor-spec.js
  specs/wp-post-nux-spec.js
  specs/wp-view-site-spec.js
Labels: [Status] Needs Review, task

#974 Add Jetpack Canary & Live Branch Support
  lib/data-helper.js
  lib/pages/wporg-creator-page.js
  magellan-jetpack-canary.json
  run.sh
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
Labels: [Status] Needs Review

#987 Update sign out button class
  lib/pages/profile-page.js
Labels: enhancement
