Repository Automattic/wp-e2e-tests, pull requests merged in 2018-07, with the labels that each got.

#1318 Try another login fix attempt
  lib/pages/login-page.js
Labels: [Status] Needs Review

#1323 Update cookies and local storage functions
  lib/driver-manager.js
Labels: [Status] Needs Review

#1322 Fix race condition mobile editor
  specs/wp-post-editor-spec.js
Labels: [Status] Needs Review

#1326 Signup: Add definition for AboutStep A/B test
  config/default.json
Labels: [Status] Needs Review

#1336 Disable 'Map a domain to an existing site'
  specs/wp-manage-domains-spec.js
Labels: workaround

#1333 Fix logins to use hooks
  lib/driver-manager.js
  specs-i18n/search-wordpress-on-google.js
  specs/wp-invite-users-spec.js
  specs/wp-log-in-out-spec.js
  specs/wp-media-upload-spec.js
  specs/wp-notifications-spec.js
  specs/wp-page-editor-spec.js
  specs/wp-plan-purchase-spec.js
  specs/wp-post-editor-spec.js
  specs/wp-reader-spec.js
  specs/wp-signup-spec.js
  specs/wp-theme-multisite-spec.js
  specs/wp-theme-switch-spec.js
  specs/wp-view-site-spec.js
Labels: [Status] Needs Review

#1338 Move setting AB test groups into StartPage
  lib/async-base-container.js
  lib/pages/signup/start-page.js
  specs/wp-invite-users-spec.js
  specs/wp-manage-domains-spec.js
  specs/wp-signup-spec.js
Labels: Technical Debt, [Status] Needs Review, [Type] Enhancement

#1339 Update 'domainSuggestionKrakenV322'
  config/default.json
Labels: [Type] Task

#1334 Add/subdomain test
  lib/pages/signup/design-type-page.js
  lib/pages/signup/start-page.js
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge

#1327 Try using mocha steps
  .eslintrc
  package-lock.json
  package.json
  specs/wp-reader-spec.js
  test/mocha.opts
Labels: [Status] Needs Review

#1324 Use data attributes for finding and removing people
  lib/pages/people-page.js
Labels: [Status] Needs Review

#1341 Add account only sign up
  specs/wp-signup-spec.js
Labels: [Type] Enhancement

#1343 Remove this.bailSuite
  docs/running-tests.md
  docs/style-guide.md
  lib/after.js
  package-lock.json
  package.json
  scripts/jetpack/wp-jetpack-activate.js
  scripts/jetpack/wp-jetpack-deactivate.js
  scripts/jetpack/wp-jetpack-jn-activate.js
  specs-i18n/logged-out-redirect-i18n-spec.js
  specs-i18n/search-wordpress-on-google.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
  specs-jetpack-calypso/wp-jetpack-onboarding-spec.js
  specs-jetpack-calypso/wp-jetpack-plans-spec.js
  specs-jetpack-calypso/wp-jetpack-plugins-spec.js
  specs-jetpack-calypso/wp-jetpack-settings-writing-media-spec.js
  specs-jetpack-calypso/wp-pressable-nux-spec.js
  specs-visdiff/wp-calypso-visdiff.js
  specs-woocommerce/wp-woocommerce-spec.js
  specs/wp-invite-users-spec.js
  specs/wp-log-in-out-spec.js
  specs/wp-manage-domains-spec.js
  specs/wp-media-upload-spec.js
  specs/wp-notifications-spec.js
  specs/wp-page-editor-spec.js
  specs/wp-plan-purchase-spec.js
  specs/wp-post-editor-spec.js
  specs/wp-signup-spec.js
  specs/wp-theme-multisite-spec.js
  specs/wp-theme-switch-spec.js
  specs/wp-view-site-spec.js
Labels: [Status] Needs Review, [Type] Enhancement

#1345 Update domain mapping spec to use new flow.
  lib/components/map-a-domain-component.js
  lib/pages/domain-my-own-page.js
  specs/wp-manage-domains-spec.js
Labels: [Status] Ready to Merge

#1344 Using sha for dserve
  docs/running-tests.md
  lib/data-helper.js
  lib/pages/login-page.js
  lib/pages/reader-manage-page.js
  lib/pages/reader-page.js
  lib/pages/signup/start-page.js
  lib/pages/themes-page.js
  run.sh
  scripts/run-wrapper.sh
  scripts/trigger-circle-ci-live-branch.sh
Labels: [Status] Ready to Merge

#1350 Add plansBannerFromDomainNudge AB test
  config/default.json
Labels: [Status] Ready to Merge

#1348 Upgrade Node to 10.6.0
  .babelrc
  .circleci/config.yml
  .nvmrc
Labels: [Type] Task

#1349 JP Plans Spec: Test if 'Renew Now' works
  lib/pages/manage-purchase-page.js
  lib/pages/purchases-page.js
  specs-jetpack-calypso/wp-jetpack-plans-spec.js
Labels: [Status] Ready to Merge

#1356 Add support for Safari Canaries
  config/default.json
  magellan-safari-canary.json
  run.sh
  specs/wp-log-in-out-spec.js
Labels: [Type] Enhancement

#1358 Adding Invite Followers test back in
  lib/pages/people-page.js
  specs/wp-invite-users-spec.js
Labels: workaround

#1359 Refactor getting URLs
  lib/data-helper.js
  lib/pages/login-page.js
  lib/pages/reader-manage-page.js
  lib/pages/reader-page.js
  lib/pages/signup/start-page.js
  lib/pages/themes-page.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review, [Type] Enhancement

#1361 Remove plansBannerFromDomainNudge
  config/default.json
Labels: [Status] Ready to Merge

#1363 Fix magic login when running locally
  lib/pages/login-page.js
Labels: [Status] Needs Review

#1367 Workaround for Category/Tags
  specs/wp-post-editor-spec.js
Labels: workaround

#1369 Retry Jetpack smoke tests in parallel
  package-lock.json
  package.json
  specs-jetpack/runner.sh
Labels: [Status] Needs Review

#1368 Domains: Add partial Transfer Domain test
  lib/pages/domain-my-own-page.js
  lib/pages/transfer-domain-page.js
  lib/pages/transfer-domain-precheck-page.js
  specs/wp-manage-domains-spec.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1374 Update sidebar button locators
  lib/components/sidebar-component.js
  specs-jetpack-calypso/wp-jetpack-plugins-spec.js
Labels: [Status] Needs Review

#1377 Kracken: Start new domain suggestion engines test v3.2.3
  config/default.json
Labels: [Status] Needs Review

#1342 Updates the e2e test as the checklist a/btest ends
  config/default.json
  lib/pages/checklist-page.js
  lib/pages/signup/about-page.js
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge
