Repository Automattic/wp-e2e-tests, pull requests merged in 2018-12, with the labels that each got.

#1679 Try to get tagged post to publish on wpcalypso
  lib/gutenberg/gutenberg-editor-sidebar-component.js
  lib/gutenberg/gutenberg-post-preview-component.js
  specs/wp-calypso-gutenberg-post-editor-spec.js
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] In Progress

#1683 Use prebuilt ffmpeg
  .circleci/config.yml
  lib/video-recorder.js
  package-lock.json
  package.json
Labels: [Status] Ready to Merge

#1681 Run tests against calypso.live if match exists in wp-calypso
  scripts/run-wrapper.sh
Labels: [Status] Ready to Merge

#1407 Update to the two factor authentication tests
  lib/driver-manager.js
  lib/email-client.js
  lib/flows/login-flow.js
  lib/pages/login-page.js
  lib/push-client.js
  lib/xmpp-client.js
  magellan-2fa.json
  package-lock.json
  package.json
  run.sh
  specs/wp-log-in-out-spec.js
Labels: [Status] Needs Secure Auth e2e Testing, [Status] Ready to Merge

#1686 Wait for radio button to show
  lib/pages/signup/checkout-page.js
Labels: [Status] Needs Review

#1688 Change path to block-editor
  lib/gutenberg/gutenberg-editor-component.js
Labels: [Status] Needs Review

#1690 Remove categories from classic editor spec
  specs/wp-post-editor-spec.js
Labels: [Status] Ready to Merge

#1692 Remove workarounds for Gutenberg editor
  specs/wp-calypso-gutenberg-page-editor-spec.js
  specs/wp-calypso-gutenberg-post-editor-spec.js
  specs/wp-gutenberg-page-editor-spec.js
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] Ready to Merge

#1693 A/B Test: add new A/B test for simplified onboarding checklist
  config/default.json
Labels: [Status] Needs Review

#1685 Check for calypso.live to be up on matching branches
  scripts/run-wrapper.sh
Labels: [Status] Needs Review

#1697 Add Embeds to Gutenberg Editor spec
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#1700 combined plan checkout page into securepayment component
  lib/components/secure-payment-component.js
  lib/pages/plan-checkout-page.js
  specs/wp-plan-purchase-spec.js
Labels: [Status] Needs Review

#1705 Wait for categoriesAndTagsSelector
  lib/components/post-editor-sidebar-component.js
Labels: [Status] Needs Review

#1704 Try using latest version of Magellan
  lib/reporter/package.json
  magellan-2fa.json
  magellan-canary.json
  magellan-i18n-nux.json
  magellan-i18n.json
  magellan-ie11-canary.json
  magellan-ie11.json
  magellan-jetpack-canary.json
  magellan-jetpack.json
  magellan-safari-canary.json
  magellan-woocommerce.json
  magellan.json
  package-lock.json
  package.json
  run.sh
Labels: [Status] Needs Jetpack e2e Testing, [Status] Needs Review

#1710 Update calypso gutenberg specs to use page preview
  specs/wp-calypso-gutenberg-page-editor-spec.js
  specs/wp-calypso-gutenberg-post-editor-spec.js
  specs/wp-gutenberg-page-editor-spec.js
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#1712 Disable tag checking in post preview
  specs/wp-calypso-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#1711 Add jetpackFreePlanButtonPosition AB test
  config/default.json
Labels: [Status] Needs Review

#1707 Wait for publishSelector, then click on it
  lib/gutenberg/gutenberg-editor-component.js
Labels: [Status] Needs Review

#1709 Clean up sidebar menu item selection
  lib/components/sidebar-component.js
Labels: [Status] Needs Jetpack e2e Testing, [Status] Ready to Merge

#1708 Updates some dependencies
  package-lock.json
  package.json
Labels: [Status] Needs Jetpack e2e Testing, [Status] Ready to Merge

#1715 Update selector for closing editor
  lib/gutenberg/gutenberg-editor-component.js
Labels: [Status] Ready to Merge

#1717 Change locators to view Drafts
  lib/pages/posts-page.js
  specs/wp-invite-users-spec.js
Labels: [Status] Needs Review

#1719 Gutenlypso: Check category in post preview
  specs/wp-calypso-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#1718 Try using fewer workers for Jetpack tests
  run.sh
Labels: [Status] Needs Jetpack e2e Testing

#1721 Remove and address sleep statement in `close-account-page.js`
  lib/pages/account/close-account-page.js
Labels: [Status] Ready to Merge

#1720 Remove and address sleep statement in `woo-wizard-jetpack-page.js`
  lib/pages/woocommerce/woo-wizard-jetpack-page.js
Labels: [Status] Ready to Merge

#1727 Remove and address sleep statement in `business-address-page.js`
  lib/pages/jetpack-onboarding/business-address-page.js
Labels: [Status] Ready to Merge

#1714 Add tests for the onboarding signup flow
  lib/override-abtest.js
  lib/pages/signup/site-info-page.js
  lib/pages/signup/site-topic-page.js
  lib/pages/signup/site-type-page.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1728 A/B Tests: Remove simplifiedChecklistView test that finished
  config/default.json
Labels: [Status] Needs Review

#1730 Update selectors for new onboarding flow
  lib/pages/signup/site-topic-page.js
Labels: [Status] Needs Review

#1731 Delete wp-gutenberg-* specs
  specs/wp-gutenberg-page-editor-spec.js
  specs/wp-gutenberg-post-editor-spec.js
Labels: [Status] Ready to Merge

#1732 Update manage domains tests to run more reliably
  lib/components/find-a-domain-component.js
  specs/wp-manage-domains-spec.js
Labels: [Status] Needs Review

#1736 Remove and address sleep statement with new `waitTillSelected` method in `site-type-page.js`
  lib/driver-helper.js
  lib/pages/signup/site-type-page.js
Labels: [Status] Ready to Merge

#1734 Remove and address sleep statement in `about-page.js`
  lib/pages/signup/about-page.js
Labels: [Status] Ready to Merge

#1726 Add new test for showConciergeSessionUpsell
  config/default.json
Labels: [Status] Needs Review

#1735 Remove and address sleep statement in `wizard-navigation-component.js`
  lib/components/wizard-navigation-component.js
Labels: [Status] Needs Jetpack e2e Testing, [Status] Needs Review

#1741 Jetpack tests: Multiple fixes
  lib/components/post-editor-sidebar-component.js
  lib/components/secure-payment-component.js
  lib/flows/login-flow.js
  lib/pages/wp-admin/wp-admin-jetpack-page.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
  specs-jetpack-calypso/wp-jetpack-onboarding-spec.js
  specs/wp-calypso-gutenberg-page-editor-spec.js
  specs/wp-comments-spec.js
Labels: [Status] Needs Review

#1738 Put back classic editor comment test
  specs/wp-comments-spec.js
Labels: [Status] Needs Jetpack e2e Testing, [Status] Needs Review

#1740 Remove and address `sleep` statement in `secure-payment-component.js`
  lib/components/secure-payment-component.js
Labels: [Status] Ready to Merge

#1742 Remove parallel tag from "Plans" test
  specs/wp-plan-purchase-spec.js
Labels: [Status] Needs Review

#1745 Fix/jetpack.com connection tests
  lib/pages/external/jetpackcom-page.js
  lib/pages/external/jetpackcom-pricing-page.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
Labels: [Status] Ready to Merge

#1744 Remove and address 2 sleep statements in `post-editor-sidebar-component.js`
  lib/components/post-editor-sidebar-component.js
Labels: [Status] Ready to Merge

#1737 Remove and address sleep statements in `wp-jetpack-plans-spec.js`
  lib/pages/jetpack-plans-sales-page.js
  lib/pages/wp-admin/wp-admin-jetpack-page.js
  specs-jetpack-calypso/wp-jetpack-plans-spec.js
Labels: [Status] Needs Jetpack e2e Testing, [Status] Needs Review

#1747 Remove 2 `sleep` statements in `wp-comments-spec.js`
  specs/wp-comments-spec.js
Labels: [Status] Ready to Merge
