Repository Automattic/wp-e2e-tests, pull requests merged in 2018-03, with the labels that each got.

#967 Add/jetpack pressable nux flow
  lib/components/sidebar-component.js
  lib/flows/pressable-nux-flow.js
  lib/pages/pressable/pressable-approve-page.js
  lib/pages/pressable/pressable-logon-page.js
  lib/pages/pressable/pressable-site-settings-page.js
  lib/pages/pressable/pressable-sites-page.js
  lib/pages/stats-page.js
  lib/pages/stats/activity-page.js
  lib/pages/wp-admin/wp-admin-dashboard-page.js
  lib/pages/wp-admin/wp-admin-sidebar.js
  specs-jetpack-calypso/wp-pressable-nux-spec.js
Labels: [Status] Needs Review

#1018 Add overrides for all known A/B tests
  config/default.json
Labels: [Status] Needs Review, enhancement

#1020 Wait for 25 seconds for finding the container element for the Jetpack Admin Page
  lib/pages/wp-admin/wp-admin-jetpack-page.js
Labels: [Pri] High, [Status] Needs Review

#1007 add Jetpack.com "Try it free" connection flow
  lib/flows/jetpack-connect-flow.js
  lib/pages/external/jetpackcom-page.js
  lib/pages/jetpack-connect-install-page.js
  lib/pages/jetpack/jetpack-connect-page.js
  lib/pages/plans-page.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
Labels: [Status] Needs Review

#1021 Switch JN tests to use stable Jetpack
  lib/pages/wp-admin/wp-admin-dashboard-page.js
  scripts/jetpack/wp-jetpack-jn-activate.js
Labels: workaround

#1028 Updating test to change case of Remove text
  lib/pages/people-page.js
Labels: [Status] Needs Review

#1029 Trying to skip through happychat prompt
  lib/pages/cancel-purchase-page.js
Labels: [Status] Needs Review

#1027 Hide environment badge for visdiff screenshots
  lib/eyes-helper.js
Labels: [Status] Needs Review, visdiffs

#1033 Cancel plan and domain all at once
  lib/pages/cancel-purchase-page.js
  specs/wp-signup-spec.js
Labels: enhancement

#1036 Fix ambiguous search locator in Plugins page
  lib/pages/plugins-browser-page.js
Labels: [Status] Ready to Merge, task

#1022 Switch back to Jetpack master for JN tests
  scripts/jetpack/wp-jetpack-jn-activate.js
Labels: [Status] Ready to Merge

#984 Add Jetpack SSO connect flow
  config/encrypted.enc
  lib/data-helper.js
  lib/flows/login-flow.js
  lib/flows/sign-up-flow.js
  lib/pages/jetpack-authorize-page.js
  lib/pages/jetpack-connect-install-page.js
  lib/pages/signup/pick-a-plan-page.js
  lib/pages/wp-admin/wp-admin-dashboard-page.js
  lib/pages/wp-admin/wp-admin-logon-page.js
  lib/pages/wp-admin/wp-admin-new-user-page.js
  lib/pages/wp-admin/wp-admin-sidebar.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
Labels: [Status] Ready to Merge

#1042 Update the revert a draft test to not expect notice
  lib/components/post-editor-toolbar-component.js
  specs/wp-post-editor-spec.js
Labels: task

#1043 Updated class selector to reflect new component in PR#23253
  lib/components/post-editor-sidebar-component.js
Labels: [Status] Ready to Merge

#1037 Add/install jetpack connect flow
  lib/pages/external/jetpackcom-features-design-page.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
Labels: [Status] Needs Review, task

#1047 Updating gsuite link
  lib/components/find-a-domain-component.js
  lib/pages/gsuite-upsell-page.js
Labels: [Status] Ready to Merge, bug

#1009 Add the `inlineHelpWithContactForm` A/B test
  config/default.json
Labels: task

#1053 Update eyes.selenium package to 0.0.78
  config/encrypted.enc
  package.json
Labels: enhancement, visdiffs

#1054 Update the `inlineHelpWithContactForm` A/B test
  config/default.json
Labels: [Status] Ready to Merge, task

#1050 Clean up sign up spec & add start of the style guide
  README.md
  docs/style-guide.md
  lib/data-helper.js
  lib/pages/signup/about-page.js
  lib/pages/signup/checkout-page.js
  specs/wp-manage-domains-spec.js
  specs/wp-signup-spec.js
Labels: enhancement

#1052 Enable Pressable NUX flow only for PRESSABLE target
  specs-jetpack-calypso/wp-pressable-nux-spec.js
Labels: [Status] Needs Review

#1056 Attempting to use the bail_time argument for magellan
  magellan-canary.json
  magellan-i18n-nux.json
  magellan-i18n.json
  magellan-ie11.json
  magellan-jetpack-canary.json
  magellan-jetpack.json
  magellan-visdiff.json
  magellan-woocommerce.json
  magellan.json
Labels: [Status] Needs Review

#1051 Try to make slack team ping works
  lib/reporter/lib/spec-xunit-reporter.js
  lib/reporter/magellan-reporter.js
Labels: [Status] Needs Review

#1058 Add mobilePlansTablesOnSignup AB test
  config/default.json
Labels: [Status] Ready to Merge

#1065 Try no customizer specific tests
  specs/wp-post-nux-spec.js
Labels: workaround

#1057 Add connect flow for Jetpack.com Paid plan from Pricing page
  lib/components/secure-payment-component.js
  lib/pages/external/jetpackcom-pricing-page.js
  lib/pages/jetpack-authorize-page.js
  lib/pages/signup/checkout-thankyou-page.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
Labels: [Status] Needs Review

#1066 Clean/map domain spec
  specs/wp-manage-domains-map-spec.js
  specs/wp-manage-domains-spec.js
Labels: [Status] Needs Review

#1063 Remove both of the minimizedFreePlan tests
  config/default.json
Labels: [Status] Needs Review

#1072 Post Editor: use the post title as the default Publicize message
  specs/wp-post-editor-spec.js
Labels: [Status] Ready to Merge

#1078 Private invites test: Delete user even if test get failed
  specs/wp-invite-users-spec.js
Labels: [Status] Needs Review

#1074 Adding time for JP authorization to complete
  lib/pages/jetpack-authorize-page.js
Labels: [Status] Needs Review

#1081 Commenting out these lines to get working for the weekend
  lib/components/post-editor-sidebar-component.js
Labels: [Status] Needs Review

#1076 Update outdated package.lock
  package-lock.json
Labels: [Type] Task

#1090 Fix IE11 sign up issues
  lib/components/find-a-domain-component.js
  lib/components/secure-payment-component.js
  lib/pages/signup/about-page.js
  lib/pages/signup/domain-first-page.js
  specs/wp-manage-domains-spec.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1093 Update magellan mocha plugin to latest version
  lib/reporter/magellan-reporter.js
  package-lock.json
  package.json
Labels: [Status] Needs Review

#1092 Secure Payment Component: Click on stored card if it's present
  lib/components/secure-payment-component.js
Labels: [Status] Needs Review

#1094 Add 'branches' target for live branch config to silence Slack
  config/encrypted.enc
Labels: [Type] Task

#1096 Cleanup debug logging from Magellan Reporter
  lib/reporter/magellan-reporter.js
Labels: [Status] Needs Review

#1088 Jetpack sites not being disconnected
  lib/components/sidebar-component.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
Labels: [Status] Ready to Merge

#1101 Add/prettier package & pre-commit hook
  .prettierignore
  package-lock.json
  package.json
  scripts/pre-commit-hook.js
Labels: [Status] Needs Review

#1086 Tests: Remove domainSearchPrefill A/B test
  config/default.json
Labels: [Status] Ready to Merge

#1097 Document the -I flag for i18n specs
  docs/running-tests.md
Labels: [Status] Ready to Merge, [Type] Enhancement

#1104 Prettify Gruntfile and ./scripts
  Gruntfile.js
  scripts/i18n-screenshots-upload.js
  scripts/launch-wpcom-login.js
Labels: [Status] Needs Review, [Type] Enhancement

#1108 Fixing mobile more button
  lib/pages/themes-page.js
Labels: [Status] Needs Review

#1110 Update mobilePlansTablesOnSignup AB test timestamp
  config/default.json
Labels: [Status] Ready to Merge
