Repository Automattic/wp-e2e-tests, pull requests merged in 2018-05, with the labels that each got.

#1171 Clarify the "why" of separate wrapper repos
  README.md
  docs/miscellaneous.md
Labels: [Status] Ready to Merge, [Type] Enhancement

#1173 Clean up the wp-signup spec
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1175 Remove temp chrome workaround
  run.sh
Labels: [Status] Needs Review

#1170 Don't wait for link in PressableSiteSettingsPage constructor
  lib/pages/pressable/pressable-site-settings-page.js
  specs-jetpack-calypso/wp-pressable-nux-spec.js
Labels: [Status] Ready to Merge

#1163 Revoke invites test
  lib/pages/invite-error-page.js
  lib/pages/people-page.js
  lib/pages/revoke-page.js
  specs/wp-invite-users-spec.js
Labels: [Status] Ready to Merge

#1182 [Domains] Add support for price strikethrough test
  config/default.json
Labels: [Status] Ready to Merge

#1184 [Domains] Tweak start date for strikethrough test
  config/default.json
Labels: [Status] Ready to Merge

#1180 Remove Upgrade Pricing Display A/B test
  config/default.json
Labels: [Status] Ready to Merge

#1183 Remove promises
  lib/components/find-a-domain-component.js
  lib/components/site-selector-component.js
  lib/media-helper.js
  specs/wp-theme-switch-spec.js
Labels: [Status] Ready to Merge

#1186 Fix failing invite tests
  lib/pages/edit-team-member-page.js
  lib/pages/invite-people-page.js
  lib/pages/people-page.js
  specs/wp-invite-users-spec.js
Labels: [Pri] High, [Status] Needs Review

#1177 Add product validation to sign up specs
  lib/components/secure-payment-component.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review, [Type] Enhancement

#1191 Add async/await into /specs-woocommerce
  lib/pages/woocommerce/add-edit-product-page.js
  specs-woocommerce/wp-woocommerce-spec.js
Labels: [Status] Ready to Merge

#1190 Add async/await into /specs-i18n
  lib/pages/landing-page.js
  specs-i18n/logged-out-redirect-i18n-spec.js
  specs-i18n/search-wordpress-on-google.js
Labels: [Status] Ready to Merge

#1189 Remove nesting in Invites tests
  lib/pages/people-page.js
  specs/wp-invite-users-spec.js
Labels: [Status] Needs Author Reply

#1195 Add async/await into /specs-visdiff
  lib/pages/editor-page.js
  specs-visdiff/wp-calypso-visdiff.js
Labels: [Status] Ready to Merge

#1202 Revert saucelabs URL to non ip address one
  lib/driver-manager.js
Labels: [Status] Needs Review

#1201 Add async/await into /specs-jetpack-calypso
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
  specs-jetpack-calypso/wp-jetpack-onboarding-spec.js
  specs-jetpack-calypso/wp-jetpack-plans-spec.js
  specs-jetpack-calypso/wp-jetpack-plugins-spec.js
  specs-jetpack-calypso/wp-jetpack-settings-writing-media-spec.js
  specs-jetpack-calypso/wp-pressable-nux-spec.js
Labels: [Status] Ready to Merge

#1194 Remove unused promises
  lib/email-client.js
  lib/pages/devdocs-page.js
  lib/pages/external/google-search.js
  lib/pages/people-page.js
  lib/push-client.js
  specs-visdiff/wp-devdocs-visdiff.js.removed
  specs-visdiff/wp-log-in-out-spec-visdiff.js.removed
  specs-visdiff/wp-page-editor-spec-password-visdiff.js.removed
  specs-visdiff/wp-page-editor-spec-private-visdiff.js.removed
  specs-visdiff/wp-page-editor-spec-public-visdiff.js.removed
Labels: [Status] Needs Review

#1192 Try adding a semi colon to javascript statement for IE11
  lib/pages/signup/signup-processing-page.js
Labels: [Status] Needs Review

#1203 Remove Promise from email client
  lib/email-client.js
Labels: [Status] Ready to Merge

#1204 Add payment button front end verification
  lib/components/payment-button-front-end-component.js
  lib/driver-helper.js
  lib/pages/editor-page.js
  lib/pages/external/paypal-checkout-page.js
  lib/pages/view-page-page.js
  lib/pages/view-post-page.js
  specs/wp-page-editor-spec.js
  specs/wp-post-editor-spec.js
Labels: [Type] Enhancement

#1205 Domains: Remove domain strikethrough price test
  config/default.json
Labels: [Status] Ready to Merge

#1208 Remove sleep in driver.quit
  lib/driver-manager.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1209 Try waiting for username field
  lib/pages/login-page.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1214 Remove .then from selectSettings() and add async/await
  lib/components/sidebar-component.js
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge

#1222 Domains: Add filter popover closure behavior test
  config/default.json
Labels: [Status] Needs Review

#1221 Make payment button tests to work with Jetpack
  config/encrypted.enc
  lib/flows/login-flow.js
  specs/wp-page-editor-spec.js
  specs/wp-post-editor-spec.js
Labels: [Status] Ready to Merge

#1218 Refactor #removeSites to not to exceed test timeouts
  lib/flows/jetpack-connect-flow.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
Labels: [Status] Ready to Merge

#1223 Update email client with latest mailosaur api
  lib/email-client.js
  lib/flows/sign-up-flow.js
  package-lock.json
  package.json
  specs/wp-invite-users-spec.js
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge, [Type] Task

#1224 Update WooCommerce test to match updated layout
  lib/pages/woocommerce/wizard-extras-page.js
  lib/pages/woocommerce/wizard-setup-page.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
Labels: [Status] Ready to Merge

#1225 Update default.json config file
  config/default.json
Labels: [Status] Needs Review, [Type] Task

#1231 Put all test artifacts into CI expected folders no matter is slack hook configured or not
  lib/reporter/magellan-reporter.js
Labels: [Status] Needs Review

#1226 Try not waiting for processing page in IE11
  lib/components/secure-payment-component.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review, [Type] Enhancement

#1236 Domains: Remove search filter closure test
  config/default.json
Labels: [Status] Blocked / Hold

#1237 Domains: Add TLD filter placement A/B definition
  config/default.json
Labels: [Status] Ready to Merge

#1235 Clean and flatten files in /specs
  lib/pages/editor-page.js
  specs/wp-invite-users-spec.js
  specs/wp-media-upload-spec.js
  specs/wp-notifications-spec.js
  specs/wp-page-editor-spec.js
  specs/wp-plan-purchase-spec.js
Labels: [Status] Needs Review, [Type] Task
