Repository Automattic/wp-e2e-tests, pull requests merged in 2018-09, with the labels that each got.

#1444 Update canaries to include paid signup (with a workaround)
  lib/flows/sign-up-flow.js
  lib/pages/signup/create-your-account-page.js
  lib/pages/signup/signup-processing-page.js
  specs/wp-post-editor-spec.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review, workaround

#1455 Disable Pressable NUX flow
  specs-jetpack-calypso/wp-pressable-nux-spec.js
Labels: [Status] Needs Review

#1449 Add readerSearchPlaceholder to known tests
  config/default.json
Labels: [Status] Ready to Merge

#1456 Add reader AB test override
  config/default.json
Labels: [Type] Task

#1446 Activity Log now accessed via side menu
  lib/components/sidebar-component.js
  lib/pages/stats-page.js
  specs-jetpack-calypso/wp-pressable-nux-spec.js
  specs/wp-post-editor-spec.js
Labels: [Status] Needs Review

#1452 Enable test for jetpack
  specs/wp-post-editor-spec.js
Labels: [Status] Ready to Merge

#1459 Remove page refresh when a/b test values are set
  lib/async-base-container.js
Labels: [Status] Needs Review

#1467 Update password in config file
  config/encrypted.enc
Labels: [Status] Needs Review

#1464 Try 8 workers for main WordPress.com e2e test runs
  magellan.json
  run.sh
Labels: [Type] Enhancement

#1470 Select a Jetpack site before navigating to A/L
  specs/wp-post-editor-spec.js
Labels: [Status] Needs Review

#1469 Update node to match wp-calypso 10.10.0
  .circleci/config.yml
  .nvmrc
Labels: [Status] Ready to Merge

#1472 Add back circleCIToken to encrypted config
  config/encrypted.enc
Labels: [Status] Ready to Merge

#1474 Themes: Update Theme Thumbnail Selector
  lib/pages/signup/choose-a-theme-page.js
  lib/pages/themes-page.js
Labels: [Status] Needs Review

#1475 Give an option for thumbnail
  lib/pages/signup/choose-a-theme-page.js
  lib/pages/themes-page.js
  package-lock.json
Labels: [Status] Needs Review

#1476 Try to fix woocommerce on mobile
  lib/driver-manager.js
  lib/pages/woocommerce/add-edit-product-page.js
Labels: workaround

#1478 Try free canary for signup
  specs/wp-signup-spec.js
Labels: workaround

#1483 Use subdomain format for livebranches
  lib/data-helper.js
  run.sh
Labels: [Status] Needs Review

#1481 Fix test run videos
  lib/driver-manager.js
Labels: [Status] Ready to Merge

#1484 Revert "Try free canary for signup (#1478)"
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1485 Add prettier ignore command to video recording arguments
  lib/driver-manager.js
Labels: [Status] Ready to Merge, [Type] Enhancement

#1482 Simulate browser Back button during sign up
  lib/pages/signup/about-page.js
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge

#1488 Add support for avoiding user first sign up flow
  config/default.json
  lib/pages/signup/jetpack-add-new-site-page.js
  lib/pages/signup/start-page.js
Labels: [Status] Ready to Merge, [Type] Enhancement, canary change

#1491 Try doing start page AB test control groups differently
  lib/async-base-container.js
  lib/pages/signup/start-page.js
Labels: [Status] Needs Review

#1480 Sync nudge a palooza tests
  config/default.json
Labels: [Status] In Progress

#1494 Skip test if domain registration is unavailable #2
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1496 Adding back in ability to use hash query param
  lib/data-helper.js
Labels: [Status] Needs Review

#1495 Use mobile emulation in Chrome to get better screen size emulation
  lib/driver-manager.js
  lib/video-recorder.js
Labels: [Status] Needs Review

#1501 A/B Tests: Add new A/B test
  config/default.json
Labels: [Status] Ready to Merge
