Repository Automattic/wp-e2e-tests, pull requests merged in 2019-03, with the labels that each got.

#1817 Fix: Update expiry date for credit card
  lib/data-helper.js
Labels: [Pri] High, [Status] Ready to Merge, [Type] Bug

#1814 Domains: No more privacy
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge

#1818 Gutenframe - updated tests
  lib/async-base-container.js
  lib/gutenberg/gutenberg-editor-component.js
  lib/gutenberg/gutenberg-page-preview-component.js
  lib/gutenberg/gutenberg-post-preview-component.js
  specs/wp-calypso-gutenberg-page-editor-spec.js
  specs/wp-calypso-gutenberg-post-editor-spec.js
Labels: [Status] In Progress

#1822 Add new AB test in default.json
  config/default.json
Labels: [Status] Needs Review

#1823 Try to improve signup test
  lib/driver-helper.js
  lib/driver-manager.js
  lib/mocha-hooks.js
  lib/override-abtest.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1825 AB Tests: Updating known A/B tests and overrides for Automattic/wp-calypso/pull/31198
  config/default.json
Labels: [Status] Ready to Merge, [Type] Task

#1824 Remove the concluded `skipBusinessInformation` test.
  config/default.json
Labels: [Status] Ready to Merge
