Repository Automattic/wp-e2e-tests, pull requests merged in 2019-02, with the labels that each got.

#1795 Restart concierge session upsell test
  config/default.json
Labels: [Status] Needs Review

#1799 Add entry for new test: twoYearPlanByDefault
  config/default.json
Labels: [Status] Needs Review

#1802 Increase timeout for signup processing to 3mins
  lib/pages/signup/signup-processing-page.js
Labels: [Status] Needs Review

#1804 Add `onlyJetpackMonthly` to known A/B tests
  config/default.json
Labels: [Status] Needs Review

#1805 Add pluginFeaturedTitle to known tests
  config/default.json
Labels: [Status] Needs Review

#1807 Remove GSuite Plan A/B Test
  config/default.json
Labels: [Status] Needs Review

#1808 Reduce timeout for signup processing to 150s
  lib/pages/signup/signup-processing-page.js
Labels: [Status] Needs Review

#1809 Add processing page step
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1787 Add "skipBusinessInformation" to the known abtest configuration.
  config/default.json
Labels: [Pri] Med, [Status] Ready to Merge

#1811 Domains: We're removing privacy subs completely
  lib/components/secure-payment-component.js
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge

#1810 Try to get signup tests passing more reliably
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge

#1789 Remove jetpackFreePlanButtonPosition AB test
  config/default.json
Labels: [Status] Ready to Merge

#1797 [WIP] Gutenberg iFrame Tests
  lib/async-base-container.js
  lib/gutenberg/gutenberg-editor-component.js
  lib/gutenberg/gutenberg-page-preview-component.js
  lib/gutenberg/gutenberg-post-preview-component.js
  specs/wp-calypso-gutenberg-page-editor-spec.js
  specs/wp-calypso-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review
