Repository Automattic/wp-e2e-tests, pull requests merged in 2019-01, with the labels that each got.

#1748 Remove `sleep` statement in `comments-area-component.js`
  lib/pages/frontend/comments-area-component.js
Labels: [Status] Ready to Merge

#1751 Clean up some unused Gutenberg code
  .gitignore
  lib/flows/login-flow.js
  lib/gutenberg/gutenberg-editor-component.js
Labels: Technical Debt, [Status] Needs Review

#1754 Fixing secure payment failures
  lib/components/secure-payment-component.js
Labels: [Status] Needs Review

#1753 Remove unused code
  lib/pages/frontend/comments-area-component.js
Labels: [Status] Ready to Merge

#1749 Remove and address 2 `sleep` statements in `wp-calypso-gutenberg-post-editor-spec.js`
  lib/gutenberg/gutenberg-editor-sidebar-component.js
  specs/wp-calypso-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#1756 Add test config for showConciergeSessionUpsellNonGSuite
  config/default.json
Labels: [Status] Ready to Merge

#1752 Re-enable the trash post steps now that they are working
  specs/wp-calypso-gutenberg-post-editor-spec.js
Labels: [Status] Ready to Merge

#1757 Signup: Update selector for new site-type step markup.
  lib/pages/signup/site-type-page.js
Labels: [Status] Ready to Merge

#1760 Fix Coupon specs on tablet
  lib/components/secure-payment-component.js
Labels: [Status] Needs Review

#1759 Update gdpr cookie to account for live branch tests
  lib/components/nav-bar-component.js
  lib/driver-manager.js
  lib/login-cookie-helper.js
Labels: [Status] Needs Review

#1762 Update login-flow to account for development environments
  lib/flows/login-flow.js
Labels: [Status] Ready to Merge

#1758 Set the expected currency
  lib/components/secure-payment-component.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1763 Fix/few more jetpack failures
  lib/components/post-editor-sidebar-component.js
  lib/driver-helper.js
  lib/pages/external/jetpackcom-features-design-page.js
  lib/pages/settings-page.js
  lib/pages/themes-page.js
  lib/pages/wporg-creator-page.js
  scripts/jetpack/wp-jetpack-jn-activate.js
  specs-blocks/gutenberg-markdown-block-spec.js
  specs-jetpack-calypso/wp-jetpack-connect-spec.js
  specs-jetpack-calypso/wp-jetpack-settings-writing-media-spec.js
  specs/wp-comments-spec.js
Labels: [Status] Ready to Merge

#1764 Improve cleanup of business sign up tests
  lib/flows/delete-account-flow.js
  lib/pages/cancel-purchase-page.js
Labels: [Status] Needs Review

#1767 Reduce number of screenshot failure slack messages
  lib/mocha-hooks.js
Labels: [Status] Needs Review

#1768 Updating `dismissAllAlerts` to use async/await style
  lib/driver-helper.js
  lib/driver-manager.js
  lib/mocha-hooks.js
  specs/wp-calypso-gutenberg-post-editor-spec.js
Labels: [Status] Needs Review

#1761 Replace the checklist with the site preview as the first thing after signing up: take 2
  lib/components/site-preview-component.js
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge

#1771 Scroll into view sectionSelector
  lib/gutenberg/gutenberg-editor-sidebar-component.js
Labels: [Status] Needs Review

#1774 Fix: Update the site info component to match the calypso-side changes
  config/default.json
  lib/pages/signup/site-info-page.js
Labels: [Status] Needs Review

#1772 Refactor: extract the common code for checking if the site preview is present.
  lib/driver-manager.js
  lib/shared-steps/wp-signup-spec.js
  specs/wp-signup-spec.js
Labels: [Status] Ready to Merge

#1779 Fixes G Suite upsell tests
  lib/components/find-a-domain-component.js
  lib/pages/gsuite-upsell-page.js
Labels: [Status] Ready to Merge

#1782 Add domainSearchButtonStyles test
  config/default.json
Labels: [Status] Ready to Merge

#1783 Test update: only the new onboarding signup variation will lead to the site preview.
  lib/shared-steps/wp-signup-spec.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1780 Fix signup spec
  lib/components/site-preview-component.js
  lib/driver-manager.js
  lib/flows/delete-account-flow.js
  lib/pages/account/account-settings-page.js
  lib/pages/cancel-domain-page.js
  lib/shared-steps/wp-signup-spec.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1788 Increase sleep delay in comments test for Jetpack sites
  specs/wp-comments-spec.js
Labels: [Status] Ready to Merge

#1790 Bump date on improved onboarding test
  config/default.json
  lib/components/inline-help-checklist-component.js
  lib/shared-steps/wp-signup-spec.js
  specs/wp-signup-spec.js
Labels: [Status] Needs Review

#1791 update config key
  config/encrypted.enc
Labels: [Status] Ready to Merge

#1785 Media editor spec
  lib/components/sidebar-component.js
  lib/pages/editor-page.js
  lib/pages/media-page.js
  specs/wp-media-editor-spec.js
  specs/wp-media-upload-spec.js
Labels: [Status] Needs Review

#1793 Update config key - part2
  config/encrypted.enc
Labels: [Status] Needs Review
